version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5
    labels: ["type/chore", "area/dependencies"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group related updates
    groups:
      dev-dependencies:
        dependency-type: "development"
        patterns: ["pytest*", "ruff", "black", "pre-commit*"]
      test-dependencies:
        patterns: ["pytest*", "coverage*", "*test*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    labels: ["type/ci", "area/dependencies"]
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
