repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Python code modernization
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-c", ".bandit.yml", "-q", "-r", "src"]
        additional_dependencies: []

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: debug-statements

  # Spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "asyn,crate,nd,te"]  # add project-specific false positives
        additional_dependencies: [tomli]
        exclude: |
          (?x)^(
              .*\.lock|
              .*\.min\.js|
              test_results/.*|
              htmlcov/.*
          )$

  # Documentation quality gates
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
        files: docs/.*\.md$

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.13.1
    hooks:
      - id: cspell
        args: ["--no-must-find-files"]
        files: docs/.*\.md$

  - repo: local
    hooks:
      # Documentation organization hooks - DISABLED to prevent commit loops
      # Use VS Code tasks or run manually instead:
      # - python scripts/organize_docs.py (all-in-one)
      # - python scripts/rename_docs.py --apply
      # - python scripts/update_doc_timestamps.py
      # - python scripts/gen_docs_index.py
      #
      # - id: docs-organize
      #   name: Organize documentation files
      #   entry: python scripts/rename_docs.py --apply
      #   language: system
      #   files: docs/.*\.md$
      #   pass_filenames: false
      # - id: docs-index
      #   name: Generate docs index
      #   entry: python scripts/gen_docs_index.py
      #   language: system
      #   files: docs/.*\.md$
      #   pass_filenames: false
      # - id: docs-touch-updated
      #   name: Update doc timestamps
      #   entry: python scripts/update_doc_timestamps.py
      #   language: system
      #   files: docs/.*\.md$
      #   pass_filenames: false
      - id: enforce-readme-lowercase
        name: Enforce readme lowercase
        entry: bash -c 'git ls-files | grep -E "(^|/)README\.md$" && { echo "❌ Use readme.md (lowercase) instead of README.md"; exit 1; } || true'
        language: system
        pass_filenames: false

# Configure which hooks run at which stages
default_stages: [pre-commit]
fail_fast: false

# CI configuration
ci:
  autofix_prs: true
  autofix_commit_msg: "style: auto-fix by pre-commit hooks"
  autoupdate_schedule: weekly
  autoupdate_commit_msg: "chore: update pre-commit hooks"
