[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "torrent-creator"
version = "1.0.0"
description = "Interactive torrent creator for qBittorrent"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "typer>=0.9.0",
    "rich>=13.7.0",
    "prompt_toolkit>=3.0.43",
    "tqdm>=4.66.1",
    "sqlalchemy>=2.0.25",
    "requests>=2.31.0",
    "python-dateutil>=2.8.2",
]

[project.scripts]
torrent-creator = "cli:main"

[tool.setuptools]
packages = ["."]
