name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint (pre-commit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      # Runs all hooks from .pre-commit-config.yaml
      - uses: pre-commit/action@v3.0.1
      # Run pyright since you have pyrightconfig.json
      - run: pip install pyright
      - run: pyright

  test:
    name: Tests (pytest)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=xml
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
