name: Release Please

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Create release and changelog
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release

      # Publish to PyPI when a release is created
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Set up Python
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: python -m build

      # Uncomment when ready to publish to PyPI
      # - name: Publish to PyPI
      #   if: ${{ steps.release.outputs.release_created }}
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      #   run: twine upload dist/*
