name: Security

on:
  pull_request:
    branches: [ main ]
    paths:
      - "**/*.py"
      - "requirements*.txt"
      - "pyproject.toml"
  push:
    branches: [ main ]
  schedule:
    # Run security scans weekly on Mondays at 5 AM UTC
    - cron: "0 5 * * 1"

permissions:
  contents: read

jobs:
  pip-audit:
    name: Dependency vulnerability scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies and pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-audit

      - name: Run pip-audit
        run: pip-audit --requirement requirements.txt --format=json --output=pip-audit-report.json

      - name: Upload pip-audit report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pip-audit-report
          path: pip-audit-report.json

  bandit:
    name: Static security analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit[toml]

      - name: Run bandit security analysis
        run: |
          bandit -f json -o bandit-report.json -r src/
          # Also run with console output for CI logs
          bandit -q -r src/ -x tests/

      - name: Upload bandit report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-report
          path: bandit-report.json
